server:
  port: 3003
  address: 0.0.0.0

spring:
  application:
    name: desafioeda

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/wallet
    url: jdbc:mysql://dbmysql:3306/wallet
    username: root
    password: root

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: root
    password: root
    #schemas:
    #- wallet
    #- microservice
    #url: jdbc:mysql://localhost:3306/wallet
    url: jdbc:mysql://dbmysql:3306/wallet
    #locations: classpath:db/migration

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    #bootstrap-servers: localhost:9092
    bootstrap-servers: kafka:29092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
